---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5022/workspace/mavenansibleapp/target/MymavenansibleWebApp.war"
        dest: "/opt/tomcat/webapps/MymavenansibleWebApp.war"

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh
        sleep 5
        /opt/tomcat/bin/startup.sh
